version: '3.8'
services:
  posgres:
    image: postgres:latest
    container_name: EventClean
    environment:
      POSTGRES_DB: EventClean
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5431:5432"
    restart: always

