spring:
  application:
    name: EventClean

  datasource:
    url: jdbc:postgresql://localhost:5431/EventClean
    username: admin
    password: admin
    driver: org.postgresql.Driver

  jpa:
    show-sql: true

  flyway:
    enable: true
